# permissions to do viewer clusterspiffeids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterspiffeid-viewer-role
rules:
- apiGroups:
  - spiffeid.io.spiffe
  resources:
  - clusterspiffeids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spiffeid.io.spiffe
  resources:
  - clusterspiffeids/status
  verbs:
  - get
