# permissions to do viewer spireentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spireentry-viewer-role
rules:
- apiGroups:
  - spiffeid.spiffe.io
  resources:
  - spireentries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spiffeid.spiffe.io
  resources:
  - spireentries/status
  verbs:
  - get
