# permissions to do edit spireentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spireentry-editor-role
rules:
- apiGroups:
  - spiffeid.spiffe.io
  resources:
  - spireentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spiffeid.spiffe.io
  resources:
  - spireentries/status
  verbs:
  - get
  - patch
  - update
